version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.0
    container_name: elasticsearch
    ports:
      - '9200:9200'
    environment:
    - discovery.type=single-node
    - xpack.security.enabled=false
    - network.host=0.0.0.0

volumes:
  es_data:
